export type PartnerCategory =
  | 'payment'
  | 'delivery'
  | 'accounting'
  | 'erp'
  | 'government'
  | 'cloud'
  | 'hardware'
  | 'loyalty'
  | 'communication'
  | 'analytics'
  | 'food_aggregator'
  | 'marketplace'
  | 'hr'
  | 'security'
  | 'reservation';

export interface TechPartner {
  id: string;
  nameEn: string;
  nameAr: string;
  category: PartnerCategory;
  description: string;
  descriptionAr: string;
  color: string;
  badge: string;
  badgeAr: string;
  region?: 'ksa' | 'gcc' | 'global';
  featured?: boolean;
}

export const PARTNER_CATEGORIES: Record<PartnerCategory, { nameAr: string; nameEn: string; icon: string; color: string }> = {
  payment:         { nameAr: 'بوابات الدفع',           nameEn: 'Payment Gateways',         icon: '💳', color: 'emerald' },
  delivery:        { nameAr: 'خدمات التوصيل',           nameEn: 'Delivery & Logistics',     icon: '🚚', color: 'orange' },
  accounting:      { nameAr: 'المحاسبة والمالية',       nameEn: 'Accounting & Finance',     icon: '📊', color: 'blue' },
  erp:             { nameAr: 'أنظمة ERP',               nameEn: 'ERP Systems',              icon: '🏭', color: 'purple' },
  government:      { nameAr: 'الجهات الحكومية',         nameEn: 'Government & Compliance',  icon: '🏛️', color: 'green' },
  cloud:           { nameAr: 'الخدمات السحابية',        nameEn: 'Cloud & Infrastructure',   icon: '☁️', color: 'sky' },
  hardware:        { nameAr: 'شركاء الأجهزة',           nameEn: 'Hardware Partners',        icon: '🖨️', color: 'slate' },
  loyalty:         { nameAr: 'الولاء والتسويق',         nameEn: 'Loyalty & Marketing',      icon: '⭐', color: 'yellow' },
  communication:   { nameAr: 'التواصل والإشعارات',      nameEn: 'Communication',            icon: '📱', color: 'indigo' },
  analytics:       { nameAr: 'التحليلات والذكاء',       nameEn: 'Analytics & BI',           icon: '📈', color: 'rose' },
  food_aggregator: { nameAr: 'منصات توصيل الطعام',      nameEn: 'Food Aggregators',         icon: '🍔', color: 'red' },
  marketplace:     { nameAr: 'المتاجر والأسواق',        nameEn: 'Marketplace & eCommerce',  icon: '🛒', color: 'amber' },
  hr:              { nameAr: 'الموارد البشرية',         nameEn: 'HR & Payroll',             icon: '👥', color: 'teal' },
  security:        { nameAr: 'الأمن والحماية',          nameEn: 'Security & Compliance',    icon: '🔐', color: 'gray' },
  reservation:     { nameAr: 'الحجوزات والمطاعم',       nameEn: 'Reservations & Dining',    icon: '📅', color: 'pink' },
};

export const TECH_PARTNERS: TechPartner[] = [

  // ══════════════════════════════════════════════════════
  //  💳  PAYMENT GATEWAYS  (30 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'geidea',          nameEn: 'Geidea',                    nameAr: 'جيدية',               category: 'payment', description: 'Saudi payment terminal & gateway',      descriptionAr: 'بوابة دفع وأجهزة POS السعودية',          color: '#1B4FBB', badge: '100% Integrated', badgeAr: 'متكامل 100%',   region: 'ksa',    featured: true },
  { id: 'mada',            nameEn: 'Mada Pay',                  nameAr: 'مدى',                 category: 'payment', description: 'Saudi national payment network',        descriptionAr: 'شبكة مدى الوطنية للدفع',                  color: '#00A651', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'ksa',    featured: true },
  { id: 'stcpay',          nameEn: 'STC Pay',                   nameAr: 'STC Pay',             category: 'payment', description: 'Digital wallet & payments',             descriptionAr: 'محفظة STC الرقمية',                        color: '#7B2D8B', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'ksa',    featured: true },
  { id: 'tamara',          nameEn: 'Tamara',                    nameAr: 'تمارا',               category: 'payment', description: 'Buy Now Pay Later (BNPL)',              descriptionAr: 'اشتر الآن وادفع لاحقاً',                   color: '#2DB8A0', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'ksa',    featured: true },
  { id: 'tabby',           nameEn: 'Tabby',                     nameAr: 'تابي',               category: 'payment', description: 'Installment payments',                 descriptionAr: 'الدفع بالتقسيط',                           color: '#3D3D3D', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'ksa' },
  { id: 'paytabs',         nameEn: 'PayTabs',                   nameAr: 'بي تابز',            category: 'payment', description: 'Online payment gateway',               descriptionAr: 'بوابة الدفع الإلكتروني',                   color: '#0072BC', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'ksa' },
  { id: 'moyasar',         nameEn: 'Moyasar',                   nameAr: 'ميسر',               category: 'payment', description: 'Saudi payment gateway API',             descriptionAr: 'بوابة دفع سعودية',                         color: '#FF6B35', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'ksa' },
  { id: 'hyperpay',        nameEn: 'HyperPay',                  nameAr: 'هايبر باي',          category: 'payment', description: 'MENA payment gateway',                 descriptionAr: 'بوابة دفع منطقة MENA',                     color: '#E63946', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'gcc' },
  { id: 'tap-payments',    nameEn: 'Tap Payments',              nameAr: 'تاب للمدفوعات',      category: 'payment', description: 'GCC payment gateway',                  descriptionAr: 'بوابة دفع خليجية',                         color: '#00ADB5', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'gcc',    featured: true },
  { id: 'payfort',         nameEn: 'Amazon Payment Services',   nameAr: 'أمازون للمدفوعات',   category: 'payment', description: 'Formerly PayFort - MENA gateway',      descriptionAr: 'باي فورت سابقاً للمنطقة العربية',          color: '#FF9900', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'gcc' },
  { id: 'stripe',          nameEn: 'Stripe',                    nameAr: 'سترايب',             category: 'payment', description: 'Global payment processing platform',   descriptionAr: 'منصة معالجة مدفوعات عالمية',               color: '#635BFF', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global', featured: true },
  { id: 'paypal',          nameEn: 'PayPal',                    nameAr: 'باي بال',            category: 'payment', description: 'Global digital wallet',                descriptionAr: 'محفظة رقمية عالمية',                       color: '#003087', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'checkout',        nameEn: 'Checkout.com',              nameAr: 'Checkout',           category: 'payment', description: 'Global payment processing',            descriptionAr: 'معالجة المدفوعات العالمية',                color: '#0033A0', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'apple-pay',       nameEn: 'Apple Pay',                 nameAr: 'Apple Pay',          category: 'payment', description: 'Contactless mobile payment',           descriptionAr: 'دفع لا تلامسي بالجوال',                   color: '#000000', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'global', featured: true },
  { id: 'google-pay',      nameEn: 'Google Pay',                nameAr: 'Google Pay',         category: 'payment', description: 'Digital wallet payments',              descriptionAr: 'محفظة Google الرقمية',                     color: '#4285F4', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'global' },
  { id: 'visa',            nameEn: 'Visa',                      nameAr: 'فيزا',               category: 'payment', description: 'Card payment acceptance',              descriptionAr: 'قبول بطاقات فيزا',                         color: '#1A1F71', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'global' },
  { id: 'mastercard',      nameEn: 'Mastercard',                nameAr: 'ماستركارد',           category: 'payment', description: 'Card payment acceptance',              descriptionAr: 'قبول بطاقات ماستركارد',                    color: '#EB001B', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'global' },
  { id: 'amex',            nameEn: 'American Express',          nameAr: 'أمريكان إكسبريس',    category: 'payment', description: 'Premium card payments',                descriptionAr: 'قبول بطاقات أمريكان إكسبريس',             color: '#016FD0', badge: 'Full Support',    badgeAr: 'دعم كامل',       region: 'global' },
  { id: 'ziina',           nameEn: 'Ziina',                     nameAr: 'زينة',               category: 'payment', description: 'UAE peer-to-peer payments',            descriptionAr: 'مدفوعات P2P إماراتية',                     color: '#6B4EFF', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'gcc' },
  { id: 'benefit',         nameEn: 'BENEFIT',                   nameAr: 'بنفت البحرين',        category: 'payment', description: 'Bahrain national payment network',     descriptionAr: 'شبكة المدفوعات الوطنية البحرينية',         color: '#00529C', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'gcc' },
  { id: 'knet',            nameEn: 'KNET',                      nameAr: 'كي نت الكويت',        category: 'payment', description: 'Kuwait national payment gateway',      descriptionAr: 'بوابة الدفع الوطنية الكويتية',             color: '#006B3C', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'gcc' },
  { id: 'fawry',           nameEn: 'Fawry',                     nameAr: 'فوري',               category: 'payment', description: 'Egyptian e-payment network',           descriptionAr: 'شبكة الدفع الإلكتروني المصرية',           color: '#F7941D', badge: 'API Ready',       badgeAr: 'API جaهز',       region: 'global' },
  { id: 'klarna',          nameEn: 'Klarna',                    nameAr: 'كلارنا',             category: 'payment', description: 'Buy now pay later global',             descriptionAr: 'اشتر الآن وادفع لاحقاً عالمياً',          color: '#FFB3C7', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'afterpay',        nameEn: 'Afterpay',                  nameAr: 'أفتر باي',           category: 'payment', description: 'BNPL payment solution',                descriptionAr: 'حل الدفع بعد الاستلام',                    color: '#B2FCE4', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'splitit',         nameEn: 'Splitit',                   nameAr: 'سبليت إت',           category: 'payment', description: 'Installment payment platform',         descriptionAr: 'منصة الدفع بالتقسيط',                     color: '#1A1A2E', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'square',          nameEn: 'Square Payments',           nameAr: 'سكوير',             category: 'payment', description: 'Point of sale & payment processing',   descriptionAr: 'نقطة بيع ومعالجة مدفوعات',                color: '#000000', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'adyen',           nameEn: 'Adyen',                     nameAr: 'آدين',               category: 'payment', description: 'Enterprise payment platform',          descriptionAr: 'منصة دفع للمؤسسات',                        color: '#0ABF53', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'worldpay',        nameEn: 'Worldpay',                  nameAr: 'ورلد باي',           category: 'payment', description: 'Global payment services',              descriptionAr: 'خدمات الدفع العالمية',                     color: '#00A4B3', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'braintree',       nameEn: 'Braintree (PayPal)',         nameAr: 'برينتري',            category: 'payment', description: 'Full-stack payment platform',          descriptionAr: 'منصة دفع متكاملة',                         color: '#1F3C88', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },
  { id: 'opay',            nameEn: 'OPay',                      nameAr: 'أو باي',             category: 'payment', description: 'Africa & MENA digital payments',       descriptionAr: 'مدفوعات رقمية أفريقيا والمنطقة',          color: '#1AA469', badge: 'API Ready',       badgeAr: 'API جاهز',       region: 'global' },

  // ══════════════════════════════════════════════════════
  //  🍔  FOOD AGGREGATORS  (18 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'hungerstation',   nameEn: 'HungerStation',             nameAr: 'هنقرستيشن',           category: 'food_aggregator', description: '#1 food delivery in Saudi Arabia', descriptionAr: 'الأول في توصيل الطعام بالسعودية', color: '#E8001C', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'ksa',    featured: true },
  { id: 'jahez',           nameEn: 'Jahez',                     nameAr: 'جاهز',               category: 'food_aggregator', description: 'Saudi food delivery platform',    descriptionAr: 'منصة توصيل الطعام السعودية',     color: '#F5A623', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'ksa',    featured: true },
  { id: 'mrsool',          nameEn: 'Mrsool',                    nameAr: 'مرسول',              category: 'food_aggregator', description: 'On-demand delivery',             descriptionAr: 'خدمة التوصيل عند الطلب',         color: '#FFB800', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'ksa' },
  { id: 'talabat',         nameEn: 'Talabat',                   nameAr: 'طلبات',              category: 'food_aggregator', description: 'GCC food delivery leader',        descriptionAr: 'رائد توصيل الطعام بالخليج',      color: '#FF6B00', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'gcc',    featured: true },
  { id: 'deliveroo',       nameEn: 'Deliveroo',                 nameAr: 'ديليفرو',            category: 'food_aggregator', description: 'Global food delivery',            descriptionAr: 'توصيل طعام عالمي',               color: '#00CCBC', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'gcc' },
  { id: 'careem-now',      nameEn: 'Careem Now',                nameAr: 'كريم ناو',            category: 'food_aggregator', description: 'Food delivery by Careem',         descriptionAr: 'توصيل طعام كريم',                color: '#6CCA98', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'gcc' },
  { id: 'noon-food',       nameEn: 'Noon Food',                 nameAr: 'نون فود',            category: 'food_aggregator', description: 'Noon food delivery service',      descriptionAr: 'خدمة توصيل طعام نون',            color: '#FEEE00', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'gcc' },
  { id: 'wolt',            nameEn: 'Wolt',                      nameAr: 'وولت',               category: 'food_aggregator', description: 'European food delivery expanding', descriptionAr: 'توصيل طعام أوروبي ومتوسع',       color: '#009DE0', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'gcc' },
  { id: 'ubereats',        nameEn: 'Uber Eats',                 nameAr: 'أوبر إيتس',          category: 'food_aggregator', description: 'Global food delivery giant',      descriptionAr: 'عملاق توصيل الطعام العالمي',     color: '#06C167', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'global', featured: true },
  { id: 'doordash',        nameEn: 'DoorDash',                  nameAr: 'دور داش',            category: 'food_aggregator', description: 'US & global food delivery',       descriptionAr: 'توصيل طعام أمريكي وعالمي',       color: '#FF3008', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'global' },
  { id: 'glovo',           nameEn: 'Glovo',                     nameAr: 'جلوفو',              category: 'food_aggregator', description: 'Multi-category delivery',         descriptionAr: 'توصيل متعدد الفئات',             color: '#FFC244', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'global' },
  { id: 'zomato',          nameEn: 'Zomato',                    nameAr: 'زوماتو',             category: 'food_aggregator', description: 'India & global food platform',    descriptionAr: 'منصة طعام هندية وعالمية',        color: '#E23744', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'global' },
  { id: 'cari',            nameEn: 'Cari',                      nameAr: 'كاري',               category: 'food_aggregator', description: 'Saudi food & grocery delivery',   descriptionAr: 'توصيل طعام وبقالة سعودي',        color: '#FF4500', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'ksa' },
  { id: 'marsool',         nameEn: 'Marsool',                   nameAr: 'مارسول',             category: 'food_aggregator', description: 'Kuwait food delivery',            descriptionAr: 'توصيل طعام كويتي',               color: '#0062CC', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'gcc' },
  { id: 'baly',            nameEn: 'Baly',                      nameAr: 'بالي',               category: 'food_aggregator', description: 'Iraq food delivery platform',     descriptionAr: 'منصة توصيل الطعام العراقية',     color: '#FF6B35', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'global' },
  { id: 'namat',           nameEn: 'Namat',                     nameAr: 'نعمت',               category: 'food_aggregator', description: 'Saudi premium food delivery',     descriptionAr: 'توصيل طعام سعودي فاخر',          color: '#8B4513', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'ksa' },
  { id: 'toyou-food',      nameEn: 'ToYou Food',                nameAr: 'توصيلك فود',         category: 'food_aggregator', description: 'Saudi food & grocery',            descriptionAr: 'طعام وبقالة سعودي',              color: '#FF4500', badge: 'Full Sync',    badgeAr: 'تزامن كامل',    region: 'ksa' },
  { id: 'mango-food',      nameEn: 'Mango',                     nameAr: 'مانجو',              category: 'food_aggregator', description: 'GCC food ordering platform',      descriptionAr: 'منصة طلب طعام خليجية',           color: '#FF8C00', badge: 'API Ready',    badgeAr: 'API جاهز',      region: 'gcc' },

  // ══════════════════════════════════════════════════════
  //  🚚  DELIVERY & LOGISTICS  (16 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'smsa',            nameEn: 'SMSA Express',              nameAr: 'SMSA إكسبريس',        category: 'delivery', description: 'Saudi express delivery',        descriptionAr: 'الشحن السريع السعودي',         color: '#003087', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'ksa',    featured: true },
  { id: 'naqel',           nameEn: 'Naqel Express',             nameAr: 'ناقل إكسبريس',        category: 'delivery', description: 'Saudi courier service',         descriptionAr: 'البريد السريع السعودي',        color: '#FF6B00', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'ksa' },
  { id: 'aramex',          nameEn: 'Aramex',                    nameAr: 'أرامكس',              category: 'delivery', description: 'Express delivery & logistics',  descriptionAr: 'الشحن والخدمات اللوجستية',    color: '#E03A28', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'gcc',    featured: true },
  { id: 'toyou',           nameEn: 'ToYou',                     nameAr: 'توصيلك',              category: 'delivery', description: 'Last-mile logistics',           descriptionAr: 'خدمة التوصيل الأخيرة',        color: '#FF4500', badge: 'Full Support', badgeAr: 'دعم كامل',   region: 'ksa' },
  { id: 'fetchr',          nameEn: 'Fetchr',                    nameAr: 'فيتشر',               category: 'delivery', description: 'UAE smart delivery',            descriptionAr: 'توصيل ذكي إماراتي',           color: '#FF6F61', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'gcc' },
  { id: 'imile',           nameEn: 'iMile',                     nameAr: 'آي مايل',             category: 'delivery', description: 'Middle East last-mile',         descriptionAr: 'توصيل الميل الأخير للمنطقة',  color: '#00B4D8', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'gcc' },
  { id: 'lalamove',        nameEn: 'Lalamove',                  nameAr: 'لالاموف',             category: 'delivery', description: 'On-demand logistics',           descriptionAr: 'خدمات لوجستية عند الطلب',     color: '#FF7A00', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'fedex',           nameEn: 'FedEx',                     nameAr: 'فيديكس',              category: 'delivery', description: 'Global express shipping',       descriptionAr: 'شحن سريع عالمي',               color: '#4D148C', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'dhl',             nameEn: 'DHL Express',               nameAr: 'DHL إكسبريس',          category: 'delivery', description: 'International logistics leader',descriptionAr: 'رائد اللوجستيات الدولية',       color: '#FFCC00', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'ups',             nameEn: 'UPS',                       nameAr: 'UPS',                  category: 'delivery', description: 'Global package delivery',       descriptionAr: 'توصيل طرود عالمي',             color: '#351C15', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'jt-express',      nameEn: 'J&T Express',               nameAr: 'J&T إكسبريس',          category: 'delivery', description: 'Fast growing courier network', descriptionAr: 'شبكة بريد سريعة النمو',        color: '#E30613', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'trukkin',         nameEn: 'Trukkin',                   nameAr: 'تراكين',              category: 'delivery', description: 'GCC truck & freight logistics', descriptionAr: 'شحن بالشاحنات بالخليج',       color: '#1F3C88', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'gcc' },
  { id: 'wakilni',         nameEn: 'Wakilni',                   nameAr: 'وكلني',               category: 'delivery', description: 'Saudi on-demand tasks',         descriptionAr: 'مهام حسب الطلب السعودية',      color: '#F5A623', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'ksa' },
  { id: 'bosta',           nameEn: 'Bosta',                     nameAr: 'بوسطة',               category: 'delivery', description: 'Egypt & MENA courier',          descriptionAr: 'بريد مصر والمنطقة',           color: '#E63946', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'shipbob',         nameEn: 'ShipBob',                   nameAr: 'شيب بوب',             category: 'delivery', description: 'eCommerce fulfillment',         descriptionAr: 'تنفيذ طلبات التجارة الإلكترونية', color: '#0066CC', badge: 'API Ready', badgeAr: 'API جاهز',   region: 'global' },
  { id: 'shippo',          nameEn: 'Shippo',                    nameAr: 'شيبو',                category: 'delivery', description: 'Multi-carrier shipping platform',descriptionAr: 'منصة شحن متعددة الناقلين',    color: '#7B2FBE', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },

  // ══════════════════════════════════════════════════════
  //  📊  ACCOUNTING & FINANCE  (18 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'quickbooks',      nameEn: 'QuickBooks Online',         nameAr: 'كويك بوكس',           category: 'accounting', description: 'Online accounting software',     descriptionAr: 'برنامج المحاسبة الإلكتروني',    color: '#2CA01C', badge: 'Full Sync',    badgeAr: 'تزامن كامل',  region: 'global', featured: true },
  { id: 'zoho-books',      nameEn: 'Zoho Books',                nameAr: 'زوهو بوكس',           category: 'accounting', description: 'Cloud accounting platform',      descriptionAr: 'منصة المحاسبة السحابية',        color: '#E42527', badge: 'Full Sync',    badgeAr: 'تزامن كامل',  region: 'global' },
  { id: 'odoo-acc',        nameEn: 'Odoo Accounting',           nameAr: 'أودو محاسبة',         category: 'accounting', description: 'Open source ERP & accounting',  descriptionAr: 'محاسبة وERP مفتوح المصدر',     color: '#714B67', badge: 'Full Sync',    badgeAr: 'تزامن كامل',  region: 'global' },
  { id: 'xero',            nameEn: 'Xero',                      nameAr: 'زيرو',                category: 'accounting', description: 'Cloud-based accounting',         descriptionAr: 'محاسبة سحابية',                color: '#13B5EA', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'sage-acc',        nameEn: 'Sage Business Cloud',       nameAr: 'سيج للأعمال',         category: 'accounting', description: 'Business accounting & finance', descriptionAr: 'محاسبة وتمويل الأعمال',        color: '#00B050', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'freshbooks',      nameEn: 'FreshBooks',                nameAr: 'فريش بوكس',           category: 'accounting', description: 'Invoice & accounting for SMEs',  descriptionAr: 'فواتير ومحاسبة للمنشآت الصغيرة', color: '#1DA462', badge: 'API Ready',  badgeAr: 'API جاهز',     region: 'global' },
  { id: 'wave-acc',        nameEn: 'Wave Accounting',           nameAr: 'ويف للمحاسبة',        category: 'accounting', description: 'Free accounting software',       descriptionAr: 'برنامج محاسبة مجاني',          color: '#0066FF', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'dafater',         nameEn: 'Dafater',                   nameAr: 'دفاتر',               category: 'accounting', description: 'Arabic accounting for SMEs',     descriptionAr: 'محاسبة عربية للمنشآت الصغيرة', color: '#2563EB', badge: 'Full Sync',    badgeAr: 'تزامن كامل',  region: 'ksa',    featured: true },
  { id: 'alfarabi',        nameEn: 'Al-Farabi ERP',             nameAr: 'الفارابي',            category: 'accounting', description: 'Saudi accounting system',        descriptionAr: 'نظام محاسبة سعودي',            color: '#10B981', badge: 'Full Sync',    badgeAr: 'تزامن كامل',  region: 'ksa' },
  { id: 'tally',           nameEn: 'Tally ERP',                 nameAr: 'تالي ERP',            category: 'accounting', description: 'Popular SME accounting',         descriptionAr: 'محاسبة شائعة للمنشآت الصغيرة', color: '#E94E1B', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'clearbooks',      nameEn: 'Clearbooks',                nameAr: 'كليرد بوكس',          category: 'accounting', description: 'Cloud accounting UK & GCC',      descriptionAr: 'محاسبة سحابية للخليج',         color: '#007BFF', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'moneybird',       nameEn: 'Moneybird',                 nameAr: 'موني بيرد',           category: 'accounting', description: 'Easy invoicing & accounting',    descriptionAr: 'فواتير ومحاسبة سهلة',          color: '#6764FF', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'holded',          nameEn: 'Holded',                    nameAr: 'هولد',                category: 'accounting', description: 'Business management platform',   descriptionAr: 'منصة إدارة الأعمال',           color: '#0099FF', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'bench',           nameEn: 'Bench',                     nameAr: 'بنش',                 category: 'accounting', description: 'Bookkeeping for small business', descriptionAr: 'مسك الدفاتر للأعمال الصغيرة',  color: '#3C5A7A', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'brightpearl',     nameEn: 'Brightpearl',               nameAr: 'برايت بيرل',          category: 'accounting', description: 'Retail management & accounting', descriptionAr: 'إدارة تجزئة ومحاسبة',          color: '#FF5722', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'mena-soft',       nameEn: 'MenaITech',                 nameAr: 'مينا آي تك',          category: 'accounting', description: 'Arabic HR & accounting',         descriptionAr: 'محاسبة وموارد بشرية عربية',    color: '#1565C0', badge: 'Full Sync',    badgeAr: 'تزامن كامل',  region: 'gcc' },
  { id: 'al-ameen',        nameEn: 'Al-Ameen Software',         nameAr: 'برنامج الأمين',        category: 'accounting', description: 'Saudi accounting system',        descriptionAr: 'نظام محاسبي سعودي',            color: '#006B3C', badge: 'Full Sync',    badgeAr: 'تزامن كامل',  region: 'ksa' },
  { id: 'kashflowapp',     nameEn: 'KashFlow',                  nameAr: 'كاش فلو',             category: 'accounting', description: 'UK cloud accounting',            descriptionAr: 'محاسبة سحابية بريطانية',        color: '#00B4A0', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },

  // ══════════════════════════════════════════════════════
  //  🏭  ERP SYSTEMS  (14 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'sap',             nameEn: 'SAP Business One',          nameAr: 'SAP بيزنس ون',        category: 'erp', description: 'Enterprise resource planning',      descriptionAr: 'تخطيط موارد المؤسسات',         color: '#0070F2', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global', featured: true },
  { id: 'oracle-netsuite', nameEn: 'Oracle NetSuite',           nameAr: 'أوراكل نيت سويت',    category: 'erp', description: 'Cloud ERP platform',                descriptionAr: 'منصة ERP سحابية',              color: '#F80000', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'ms-dynamics',     nameEn: 'Microsoft Dynamics 365',    nameAr: 'مايكروسوفت دايناميكس',category: 'erp', description: 'Integrated business applications',  descriptionAr: 'تطبيقات أعمال متكاملة',        color: '#0078D4', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'odoo-erp',        nameEn: 'Odoo ERP',                  nameAr: 'أودو ERP',            category: 'erp', description: 'All-in-one ERP solution',           descriptionAr: 'حل ERP متكامل',                color: '#714B67', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'global', featured: true },
  { id: 'mena-erp',        nameEn: 'MENA ERP',                  nameAr: 'مينا ERP',            category: 'erp', description: 'Arabic ERP for Middle East',        descriptionAr: 'ERP عربي للشرق الأوسط',        color: '#1D4ED8', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'gcc' },
  { id: 'epicor',          nameEn: 'Epicor ERP',                nameAr: 'إبيكور',             category: 'erp', description: 'Manufacturing & distribution ERP',  descriptionAr: 'ERP للتصنيع والتوزيع',         color: '#D4000C', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'infor',           nameEn: 'Infor CloudSuite',          nameAr: 'إنفور كلاود سويت',    category: 'erp', description: 'Industry-specific cloud ERP',       descriptionAr: 'ERP سحابي متخصص للصناعة',      color: '#0088CE', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'acumatica',       nameEn: 'Acumatica',                 nameAr: 'أكوماتيكا',           category: 'erp', description: 'Cloud ERP for SMEs',                descriptionAr: 'ERP سحابي للمنشآت المتوسطة',   color: '#CB2128', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'ifs-erp',         nameEn: 'IFS Applications',          nameAr: 'IFS تطبيقات',        category: 'erp', description: 'Service & manufacturing ERP',       descriptionAr: 'ERP للخدمات والتصنيع',         color: '#00599D', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'syspro',          nameEn: 'SYSPRO',                    nameAr: 'سيسبرو',             category: 'erp', description: 'Manufacturing ERP system',           descriptionAr: 'نظام ERP للتصنيع',             color: '#FF5000', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'sage-x3',         nameEn: 'Sage X3',                   nameAr: 'سيج X3',             category: 'erp', description: 'Enterprise ERP & management',       descriptionAr: 'ERP وإدارة المؤسسات',          color: '#00B050', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'netsol',          nameEn: 'NetSol Technologies',       nameAr: 'نت سول تكنولوجيز',    category: 'erp', description: 'Finance & ERP for MENA',            descriptionAr: 'مالية وERP لمنطقة MENA',       color: '#005B96', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'gcc' },
  { id: 'ramco',           nameEn: 'Ramco Systems',             nameAr: 'رامكو سيستمز',        category: 'erp', description: 'Cloud ERP for services',            descriptionAr: 'ERP سحابي للخدمات',           color: '#E2031F', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'unit4',           nameEn: 'Unit4',                     nameAr: 'يونيت 4',             category: 'erp', description: 'People-centric ERP',                descriptionAr: 'ERP محوره الإنسان',            color: '#FF6600', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },

  // ══════════════════════════════════════════════════════
  //  🏛️  GOVERNMENT & COMPLIANCE  (14 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'zatca',           nameEn: 'ZATCA (Fatoorah)',          nameAr: 'هيئة الزكاة والضريبة', category: 'government', description: 'Saudi e-invoicing (Phase 1 & 2)', descriptionAr: 'الفاتورة الإلكترونية المرحلة 1 و2', color: '#006C35', badge: '✅ Certified', badgeAr: '✅ معتمد',  region: 'ksa', featured: true },
  { id: 'gosi',            nameEn: 'GOSI',                      nameAr: 'التأمينات الاجتماعية',  category: 'government', description: 'Social insurance organization',   descriptionAr: 'المؤسسة العامة للتأمينات',          color: '#006600', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa', featured: true },
  { id: 'qiwa',            nameEn: 'Qiwa Platform',             nameAr: 'منصة قوى',             category: 'government', description: 'Saudi labor portal',              descriptionAr: 'بوابة العمل السعودية',               color: '#006B77', badge: 'Full Support', badgeAr: 'دعم كامل',  region: 'ksa', featured: true },
  { id: 'mudad',           nameEn: 'Mudad (WPS)',               nameAr: 'مدد حماية الأجور',      category: 'government', description: 'Wage protection system',          descriptionAr: 'نظام حماية الأجور',                 color: '#1A3A6E', badge: 'Full Support', badgeAr: 'دعم كامل',  region: 'ksa', featured: true },
  { id: 'etimad',          nameEn: 'Etimad',                    nameAr: 'اعتماد',                category: 'government', description: 'Saudi government payments',       descriptionAr: 'منصة حكومية للمدفوعات',             color: '#006C35', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'absher',          nameEn: 'Absher Business',           nameAr: 'أبشر أعمال',            category: 'government', description: 'Government services platform',    descriptionAr: 'منصة الخدمات الحكومية',             color: '#005F87', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'maroof',          nameEn: 'Maroof',                    nameAr: 'معروف',                 category: 'government', description: 'Business verification platform',  descriptionAr: 'منصة التحقق من الأعمال',            color: '#2D6A4F', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'taqat',           nameEn: 'Taqat (Hadaf)',             nameAr: 'طاقات / هدف',           category: 'government', description: 'Saudi employment portal',         descriptionAr: 'بوابة التوظيف السعودية',            color: '#1D4ED8', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'bayan',           nameEn: 'Bayan Platform',            nameAr: 'منصة بيان',             category: 'government', description: 'Saudi customs clearance',         descriptionAr: 'التخليص الجمركي السعودي',           color: '#7C3AED', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'wafi',            nameEn: 'Wafi',                      nameAr: 'وافي',                  category: 'government', description: 'Saudi digital governance',        descriptionAr: 'الحوكمة الرقمية السعودية',          color: '#059669', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'masar',           nameEn: 'Masar',                     nameAr: 'مسار',                  category: 'government', description: 'Saudi logistics platform',        descriptionAr: 'منصة اللوجستيات السعودية',          color: '#0284C7', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'maaref',          nameEn: 'Maaref',                    nameAr: 'معارف',                 category: 'government', description: 'Saudi education platform',        descriptionAr: 'منصة التعليم السعودية',             color: '#047857', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'ksa' },
  { id: 'my-gov-uae',      nameEn: 'UAE ADDA',                  nameAr: 'دائرة المالية أبوظبي',  category: 'government', description: 'Abu Dhabi financial authority',   descriptionAr: 'الدائرة المالية لأبوظبي',           color: '#007B5F', badge: 'API Ready',    badgeAr: 'API جاهز',  region: 'gcc' },
  { id: 'pci-dss',         nameEn: 'PCI DSS Compliance',        nameAr: 'معايير PCI DSS',        category: 'government', description: 'Payment card security standard', descriptionAr: 'معيار أمان بطاقات الدفع',           color: '#003087', badge: 'Compliant',   badgeAr: 'ممتثل',     region: 'global', featured: true },

  // ══════════════════════════════════════════════════════
  //  ☁️  CLOUD & INFRASTRUCTURE  (16 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'aws',             nameEn: 'Amazon Web Services',       nameAr: 'Amazon AWS',          category: 'cloud', description: 'Cloud computing platform',      descriptionAr: 'منصة الحوسبة السحابية',       color: '#FF9900', badge: 'Hosted',       badgeAr: 'مستضاف',   region: 'global', featured: true },
  { id: 'gcp',             nameEn: 'Google Cloud',              nameAr: 'Google Cloud',        category: 'cloud', description: 'Cloud platform & services',     descriptionAr: 'خدمات وحوسبة سحابية',         color: '#4285F4', badge: 'Hosted',       badgeAr: 'مستضاف',   region: 'global' },
  { id: 'azure',           nameEn: 'Microsoft Azure',           nameAr: 'مايكروسوفت أزور',     category: 'cloud', description: 'Cloud computing services',      descriptionAr: 'خدمات الحوسبة السحابية',       color: '#0078D4', badge: 'Hosted',       badgeAr: 'مستضاف',   region: 'global' },
  { id: 'alibaba-cloud',   nameEn: 'Alibaba Cloud',             nameAr: 'علي بابا كلاود',      category: 'cloud', description: 'Asia-Pacific cloud leader',     descriptionAr: 'رائد السحابة في آسيا',         color: '#FF6A00', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'oracle-cloud',    nameEn: 'Oracle Cloud',              nameAr: 'أوراكل كلاود',        category: 'cloud', description: 'Enterprise cloud infrastructure',descriptionAr: 'بنية سحابية للمؤسسات',         color: '#F80000', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'ibm-cloud',       nameEn: 'IBM Cloud',                 nameAr: 'IBM كلاود',           category: 'cloud', description: 'Hybrid cloud solutions',        descriptionAr: 'حلول السحابة الهجينة',         color: '#1F70C1', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'cloudflare',      nameEn: 'Cloudflare',                nameAr: 'كلاودفلير',           category: 'cloud', description: 'CDN & security services',       descriptionAr: 'CDN وخدمات الأمان',            color: '#F48120', badge: 'Active',       badgeAr: 'نشط',      region: 'global', featured: true },
  { id: 'mongodb-atlas',   nameEn: 'MongoDB Atlas',             nameAr: 'MongoDB أطلس',        category: 'cloud', description: 'Cloud database service',        descriptionAr: 'قاعدة بيانات سحابية',          color: '#00ED64', badge: 'Active DB',    badgeAr: 'قاعدة البيانات', region: 'global', featured: true },
  { id: 'digitalocean',    nameEn: 'DigitalOcean',              nameAr: 'ديجيتال أوشن',        category: 'cloud', description: 'Developer cloud platform',      descriptionAr: 'منصة سحابة للمطورين',          color: '#0080FF', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'hetzner',         nameEn: 'Hetzner Cloud',             nameAr: 'هيتزنر كلاود',        category: 'cloud', description: 'European cloud hosting',        descriptionAr: 'استضافة سحابية أوروبية',        color: '#D50C2D', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'ovhcloud',        nameEn: 'OVHcloud',                  nameAr: 'OVH كلاود',           category: 'cloud', description: 'European cloud services',       descriptionAr: 'خدمات سحابية أوروبية',         color: '#123F6D', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'vultr',           nameEn: 'Vultr',                     nameAr: 'فالتر',               category: 'cloud', description: 'High performance cloud',        descriptionAr: 'سحابة عالية الأداء',           color: '#007BFC', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'linode',          nameEn: 'Akamai (Linode)',           nameAr: 'أكاماي / لينود',      category: 'cloud', description: 'Developer cloud & CDN',         descriptionAr: 'سحابة مطورين وCDN',            color: '#00A95C', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'firebase',        nameEn: 'Firebase (Google)',          nameAr: 'Firebase',            category: 'cloud', description: 'App backend & push notifications',descriptionAr: 'خلفية التطبيق وإشعارات فورية',  color: '#FFA000', badge: 'Active',       badgeAr: 'نشط',      region: 'global', featured: true },
  { id: 'supabase',        nameEn: 'Supabase',                  nameAr: 'سوبابيس',             category: 'cloud', description: 'Open source Firebase alternative',descriptionAr: 'بديل مفتوح المصدر لـ Firebase', color: '#3ECF8E', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'vercel',          nameEn: 'Vercel',                    nameAr: 'فيرسل',               category: 'cloud', description: 'Frontend cloud platform',       descriptionAr: 'منصة سحابية للواجهة الأمامية',  color: '#000000', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },

  // ══════════════════════════════════════════════════════
  //  🖨️  HARDWARE PARTNERS  (18 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'sunmi-hw',        nameEn: 'Sunmi Technology',          nameAr: 'سونمي تكنولوجي',      category: 'hardware', description: 'POS terminals & Android devices', descriptionAr: 'أجهزة POS وأندرويد', color: '#1E3A5F', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global', featured: true },
  { id: 'epson-hw',        nameEn: 'Epson',                     nameAr: 'إبسون',               category: 'hardware', description: 'Thermal receipt & label printers', descriptionAr: 'طابعات حرارية وملصقات',    color: '#004B96', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global', featured: true },
  { id: 'zkteco-hw',       nameEn: 'ZKTeco',                    nameAr: 'ZK تيكو',             category: 'hardware', description: 'Fingerprint & access control',     descriptionAr: 'بصمة والتحكم بالدخول',    color: '#0066CC', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global', featured: true },
  { id: 'star-hw',         nameEn: 'Star Micronics',            nameAr: 'ستار مايكرونكس',      category: 'hardware', description: 'POS receipt printers',             descriptionAr: 'طابعات إيصالات POS',       color: '#003087', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'bixolon-hw',      nameEn: 'Bixolon',                   nameAr: 'بيكسولون',            category: 'hardware', description: 'POS printers & scanners',          descriptionAr: 'طابعات POS وماسحات',       color: '#003366', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'imin-hw',         nameEn: 'IMIN Technology',           nameAr: 'إيمن تكنولوجي',       category: 'hardware', description: 'Smart POS terminals',              descriptionAr: 'أجهزة POS الذكية',         color: '#FF4E00', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'zebra-hw',        nameEn: 'Zebra Technologies',        nameAr: 'زيبرا تكنولوجيز',     category: 'hardware', description: 'Scanners & label printers',         descriptionAr: 'ماسحات وطابعات ملصقات',   color: '#1F6B75', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'honeywell-hw',    nameEn: 'Honeywell',                 nameAr: 'هانيول',              category: 'hardware', description: 'Barcode scanners',                 descriptionAr: 'ماسحات باركود',            color: '#ED2024', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'ingenico-hw',     nameEn: 'Ingenico',                  nameAr: 'إنجينيكو',            category: 'hardware', description: 'Payment terminals',                descriptionAr: 'أجهزة الدفع الإلكتروني',  color: '#004B84', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'verifone-hw',     nameEn: 'Verifone',                  nameAr: 'فيريفون',             category: 'hardware', description: 'POS payment terminals',            descriptionAr: 'أجهزة دفع POS',            color: '#005CA9', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'pax-hw',          nameEn: 'PAX Technology',            nameAr: 'باكس تكنولوجي',       category: 'hardware', description: 'Smart payment terminals',          descriptionAr: 'أجهزة دفع ذكية',          color: '#0057A8', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'ncr-hw',          nameEn: 'NCR Voyix',                 nameAr: 'NCR فويكس',           category: 'hardware', description: 'POS & self-service kiosks',        descriptionAr: 'POS وأكشاك الخدمة الذاتية', color: '#CC0000', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'posiflex-hw',     nameEn: 'Posiflex',                  nameAr: 'بوسيفلكس',            category: 'hardware', description: 'POS terminals & printers',         descriptionAr: 'أجهزة وطابعات POS',        color: '#003366', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'newland-hw',      nameEn: 'Newland',                   nameAr: 'نيولاند',             category: 'hardware', description: 'Barcode scanners & POS',           descriptionAr: 'ماسحات باركود وأجهزة POS', color: '#E74C3C', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'datalogic-hw',    nameEn: 'Datalogic',                 nameAr: 'داتالوجيك',           category: 'hardware', description: 'Industrial barcode scanners',      descriptionAr: 'ماسحات باركود صناعية',     color: '#D40000', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'telpo-hw',        nameEn: 'Telpo',                     nameAr: 'تيلبو',               category: 'hardware', description: 'Smart POS & kiosk solutions',      descriptionAr: 'حلول POS وأكشاك ذكية',    color: '#FF6B35', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'urovo-hw',        nameEn: 'Urovo',                     nameAr: 'يوروفو',              category: 'hardware', description: 'Mobile data terminals',            descriptionAr: 'محطات بيانات متنقلة',      color: '#0066CC', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },
  { id: 'elo-hw',          nameEn: 'Elo Touch',                 nameAr: 'إيلو تاتش',           category: 'hardware', description: 'Touch screens & kiosks',           descriptionAr: 'شاشات لمس وأكشاك تفاعلية', color: '#0099CC', badge: '100% Compatible', badgeAr: 'متوافق 100%', region: 'global' },

  // ══════════════════════════════════════════════════════
  //  📱  COMMUNICATION  (16 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'whatsapp',        nameEn: 'WhatsApp Business API',     nameAr: 'واتساب بيزنس',        category: 'communication', description: 'Customer notifications via WhatsApp', descriptionAr: 'إشعارات عبر واتساب',       color: '#25D366', badge: 'Full Support', badgeAr: 'دعم كامل', region: 'global', featured: true },
  { id: 'firebase-fcm',    nameEn: 'Firebase Cloud Messaging',  nameAr: 'Firebase FCM',        category: 'communication', description: 'Push notifications platform',        descriptionAr: 'إشعارات فورية للتطبيقات', color: '#FFA000', badge: 'Active',       badgeAr: 'نشط',      region: 'global', featured: true },
  { id: 'twilio',          nameEn: 'Twilio',                    nameAr: 'تويليو',              category: 'communication', description: 'SMS & voice communications',         descriptionAr: 'رسائل SMS واتصالات',        color: '#F22F46', badge: 'Full Support', badgeAr: 'دعم كامل', region: 'global' },
  { id: 'sendgrid',        nameEn: 'SendGrid',                  nameAr: 'SendGrid',            category: 'communication', description: 'Transactional email service',        descriptionAr: 'خدمة البريد الإلكتروني',   color: '#1A82E2', badge: 'Active',       badgeAr: 'نشط',      region: 'global' },
  { id: 'unifonic',        nameEn: 'Unifonic',                  nameAr: 'يونيفونيك',           category: 'communication', description: 'Saudi SMS & WhatsApp platform',      descriptionAr: 'منصة رسائل سعودية',        color: '#FF6B35', badge: 'Full Support', badgeAr: 'دعم كامل', region: 'ksa',    featured: true },
  { id: 'msegat',          nameEn: 'Msegat',                    nameAr: 'مسجات',               category: 'communication', description: 'Arabic SMS platform',               descriptionAr: 'منصة رسائل SMS عربية',     color: '#E74C3C', badge: 'Full Support', badgeAr: 'دعم كامل', region: 'ksa' },
  { id: 'infobip',         nameEn: 'Infobip',                   nameAr: 'إنفوبيب',             category: 'communication', description: 'Omnichannel communication',          descriptionAr: 'تواصل متعدد القنوات',      color: '#E91E63', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'messagebird',     nameEn: 'MessageBird (Bird)',        nameAr: 'ميسيج بيرد',          category: 'communication', description: 'Omnichannel messaging platform',     descriptionAr: 'منصة رسائل متعددة القنوات', color: '#2481D7', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'vonage',          nameEn: 'Vonage (Ericsson)',         nameAr: 'فوناج',               category: 'communication', description: 'Cloud communications API',           descriptionAr: 'API اتصالات سحابية',       color: '#6E00CC', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'nexmo',           nameEn: 'Nexmo (Vonage)',            nameAr: 'نيكسمو',              category: 'communication', description: 'SMS & voice API',                   descriptionAr: 'SMS وAPI صوتي',            color: '#6E00CC', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'plivo',           nameEn: 'Plivo',                     nameAr: 'بليفو',               category: 'communication', description: 'SMS & voice cloud',                 descriptionAr: 'SMS وسحابة صوتية',         color: '#FF5722', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'mailgun',         nameEn: 'Mailgun',                   nameAr: 'ميل جن',              category: 'communication', description: 'Developer email API',               descriptionAr: 'API بريد إلكتروني للمطورين', color: '#F06B00', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'postmark',        nameEn: 'Postmark',                  nameAr: 'بوست مارك',           category: 'communication', description: 'Transactional email delivery',       descriptionAr: 'تسليم البريد الإلكتروني',  color: '#FFDE00', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'onesignal',       nameEn: 'OneSignal',                 nameAr: 'ون سيجنال',           category: 'communication', description: 'Push notification platform',         descriptionAr: 'منصة إشعارات دفع',         color: '#E54B4D', badge: 'Full Support', badgeAr: 'دعم كامل', region: 'global' },
  { id: 'klaviyo-email',   nameEn: 'Klaviyo',                   nameAr: 'كلافيو',              category: 'communication', description: 'Email & SMS marketing automation',   descriptionAr: 'أتمتة بريد ورسائل تسويقية', color: '#1A1A1A', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },
  { id: 'intercom',        nameEn: 'Intercom',                  nameAr: 'إنتركوم',             category: 'communication', description: 'Customer messaging platform',        descriptionAr: 'منصة مراسلة العملاء',      color: '#1F8DED', badge: 'API Ready',    badgeAr: 'API جاهز', region: 'global' },

  // ══════════════════════════════════════════════════════
  //  📈  ANALYTICS & BI  (14 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'google-analytics',nameEn: 'Google Analytics 4',        nameAr: 'Google Analytics',    category: 'analytics', description: 'Web & app analytics',          descriptionAr: 'تحليلات الويب والتطبيقات',  color: '#E37400', badge: 'Active',       badgeAr: 'نشط',          region: 'global', featured: true },
  { id: 'meta-business',   nameEn: 'Meta Business Suite',       nameAr: 'Meta أعمال',          category: 'analytics', description: 'Facebook & Instagram insights',descriptionAr: 'إحصاءات فيسبوك وإنستغرام', color: '#1877F2', badge: 'Active',       badgeAr: 'نشط',          region: 'global' },
  { id: 'mixpanel',        nameEn: 'Mixpanel',                  nameAr: 'ميكس بانل',           category: 'analytics', description: 'Product analytics platform',   descriptionAr: 'منصة تحليل المنتج',         color: '#7856FF', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'powerbi',         nameEn: 'Microsoft Power BI',        nameAr: 'Power BI',            category: 'analytics', description: 'Business intelligence',        descriptionAr: 'ذكاء الأعمال والتقارير',    color: '#F2C811', badge: 'Export Ready', badgeAr: 'تصدير جاهز',   region: 'global', featured: true },
  { id: 'tableau',         nameEn: 'Tableau (Salesforce)',      nameAr: 'تابلو',               category: 'analytics', description: 'Data visualization platform',  descriptionAr: 'منصة تصور البيانات',        color: '#E97627', badge: 'Export Ready', badgeAr: 'تصدير جاهز',   region: 'global' },
  { id: 'looker',          nameEn: 'Google Looker Studio',      nameAr: 'Looker Studio',       category: 'analytics', description: 'Data reports & dashboards',    descriptionAr: 'تقارير ولوحات بيانات',     color: '#4285F4', badge: 'Export Ready', badgeAr: 'تصدير جاهز',   region: 'global' },
  { id: 'amplitude',       nameEn: 'Amplitude',                 nameAr: 'أمبليتيود',           category: 'analytics', description: 'Digital analytics platform',   descriptionAr: 'منصة تحليل رقمية',         color: '#0066FF', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'heap',            nameEn: 'Heap Analytics',            nameAr: 'هيب للتحليل',         category: 'analytics', description: 'Automatic user analytics',     descriptionAr: 'تحليل مستخدم تلقائي',      color: '#FF5700', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'hotjar',          nameEn: 'Hotjar',                    nameAr: 'هوت جار',             category: 'analytics', description: 'Heatmaps & user recordings',   descriptionAr: 'خرائط حرارية وتسجيلات',    color: '#FF3C00', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'segment',         nameEn: 'Segment (Twilio)',          nameAr: 'سيجمنت',              category: 'analytics', description: 'Customer data platform',       descriptionAr: 'منصة بيانات العملاء',       color: '#52BD94', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'qlik',            nameEn: 'Qlik Sense',                nameAr: 'كليك سينس',           category: 'analytics', description: 'Business intelligence & analytics', descriptionAr: 'ذكاء أعمال وتحليلات',   color: '#009845', badge: 'Export Ready', badgeAr: 'تصدير جاهز',   region: 'global' },
  { id: 'domo',            nameEn: 'Domo',                      nameAr: 'دومو',                category: 'analytics', description: 'Cloud BI & data platform',     descriptionAr: 'منصة BI والبيانات السحابية', color: '#00A1E0', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'tiktok-analytics',nameEn: 'TikTok Business',           nameAr: 'تيك توك للأعمال',     category: 'analytics', description: 'TikTok ads & analytics',       descriptionAr: 'إعلانات وتحليلات تيك توك', color: '#010101', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },
  { id: 'snap-ads',        nameEn: 'Snapchat Ads Manager',      nameAr: 'سناب للإعلانات',      category: 'analytics', description: 'Snapchat advertising platform', descriptionAr: 'منصة إعلانات سناب شات',    color: '#FFFC00', badge: 'API Ready',    badgeAr: 'API جاهز',     region: 'global' },

  // ══════════════════════════════════════════════════════
  //  ⭐  LOYALTY & MARKETING  (14 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'mailchimp',       nameEn: 'Mailchimp',                 nameAr: 'ميل شيمب',            category: 'loyalty', description: 'Email marketing automation',      descriptionAr: 'أتمتة التسويق بالبريد',     color: '#FFE01B', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'global' },
  { id: 'hubspot',         nameEn: 'HubSpot CRM',               nameAr: 'هاب سبوت CRM',        category: 'loyalty', description: 'Customer relationship management', descriptionAr: 'إدارة علاقات العملاء',       color: '#FF7A59', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global', featured: true },
  { id: 'smile-io',        nameEn: 'Smile.io',                  nameAr: 'سمايل Loyalty',       category: 'loyalty', description: 'Loyalty & rewards program',        descriptionAr: 'برنامج الولاء والمكافآت',    color: '#FF7C4C', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'braze',           nameEn: 'Braze',                     nameAr: 'بريز',                category: 'loyalty', description: 'Customer engagement platform',     descriptionAr: 'منصة تفاعل العملاء',         color: '#F26625', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'salesforce',      nameEn: 'Salesforce',                nameAr: 'سيلز فورس',           category: 'loyalty', description: 'World\'s #1 CRM platform',        descriptionAr: 'المنصة الأولى عالمياً للـ CRM', color: '#00A1E0', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global', featured: true },
  { id: 'yotpo',           nameEn: 'Yotpo',                     nameAr: 'يوتبو',               category: 'loyalty', description: 'Reviews & loyalty platform',       descriptionAr: 'منصة المراجعات والولاء',     color: '#ED5432', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'loyalty-lion',    nameEn: 'LoyaltyLion',               nameAr: 'لويالتي لايون',        category: 'loyalty', description: 'eCommerce loyalty platform',       descriptionAr: 'منصة ولاء للتجارة الإلكترونية', color: '#1D2C3A', badge: 'API Ready', badgeAr: 'API جاهز',   region: 'global' },
  { id: 'antavo',          nameEn: 'Antavo',                    nameAr: 'أنتافو',              category: 'loyalty', description: 'Enterprise loyalty technology',    descriptionAr: 'تكنولوجيا ولاء للمؤسسات',   color: '#6C4AB6', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'sessionm',        nameEn: 'SessionM (Mastercard)',     nameAr: 'سيشن إم',             category: 'loyalty', description: 'Customer loyalty management',      descriptionAr: 'إدارة ولاء العملاء',         color: '#EB001B', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'drip',            nameEn: 'Drip',                      nameAr: 'دريب',                category: 'loyalty', description: 'eCommerce marketing automation',   descriptionAr: 'أتمتة تسويق للتجارة الإلكترونية', color: '#EA4B71', badge: 'API Ready', badgeAr: 'API جاهز',   region: 'global' },
  { id: 'active-campaign', nameEn: 'ActiveCampaign',            nameAr: 'أكتيف كامبين',        category: 'loyalty', description: 'Email & CRM automation',           descriptionAr: 'أتمتة بريد وCRM',           color: '#356AE6', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'zoho-crm',        nameEn: 'Zoho CRM',                  nameAr: 'زوهو CRM',            category: 'loyalty', description: 'Customer relationship platform',   descriptionAr: 'منصة علاقات العملاء',        color: '#E42527', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'convertkit',      nameEn: 'ConvertKit',                nameAr: 'كونفيرت كيت',         category: 'loyalty', description: 'Creator email marketing',          descriptionAr: 'تسويق بريدي للمبدعين',      color: '#FB6970', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'loyalty-genie',   nameEn: 'Loyalty Genie',             nameAr: 'لويالتي جيني',         category: 'loyalty', description: 'GCC loyalty program builder',      descriptionAr: 'بناء برامج ولاء خليجية',    color: '#FF8C00', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'gcc' },

  // ══════════════════════════════════════════════════════
  //  👥  HR & PAYROLL  (14 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'qiwa-hr',         nameEn: 'Qiwa Platform',             nameAr: 'منصة قوى',            category: 'hr', description: 'Saudi labor portal',          descriptionAr: 'بوابة العمل السعودية',      color: '#006B77', badge: 'Full Support', badgeAr: 'دعم كامل',    region: 'ksa', featured: true },
  { id: 'mudad-hr',        nameEn: 'Mudad',                     nameAr: 'مدد',                 category: 'hr', description: 'Wage protection & payroll',    descriptionAr: 'حماية الأجور والرواتب',     color: '#1A3A6E', badge: 'Full Support', badgeAr: 'دعم كامل',    region: 'ksa', featured: true },
  { id: 'mawared',         nameEn: 'Mawared',                   nameAr: 'موارد',               category: 'hr', description: 'Saudi HR management system',  descriptionAr: 'نظام إدارة الموارد البشرية', color: '#1D4ED8', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'ksa' },
  { id: 'bayzat',          nameEn: 'Bayzat',                    nameAr: 'بيزات',               category: 'hr', description: 'HR & payroll management',     descriptionAr: 'إدارة الموارد البشرية',     color: '#0056B3', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'gcc' },
  { id: 'workday',         nameEn: 'Workday HCM',               nameAr: 'ووركداي HCM',         category: 'hr', description: 'Enterprise HR & finance',     descriptionAr: 'موارد بشرية ومالية للمؤسسات', color: '#009EDB', badge: 'API Ready',   badgeAr: 'API جاهز',    region: 'global' },
  { id: 'sap-hcm',         nameEn: 'SAP SuccessFactors',        nameAr: 'SAP سكسيس فاكتورز',   category: 'hr', description: 'HR cloud suite',              descriptionAr: 'مجموعة HR السحابية',        color: '#0070F2', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'bamboohr',        nameEn: 'BambooHR',                  nameAr: 'بامبو HR',            category: 'hr', description: 'HR software for SMBs',        descriptionAr: 'برنامج HR للمنشآت الصغيرة', color: '#73AA24', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'adp',             nameEn: 'ADP Payroll',               nameAr: 'ADP للرواتب',         category: 'hr', description: 'Payroll & HR services',       descriptionAr: 'رواتب وخدمات موارد بشرية', color: '#D50032', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'gusto',           nameEn: 'Gusto',                     nameAr: 'جوستو',               category: 'hr', description: 'Payroll & benefits platform', descriptionAr: 'منصة رواتب ومزايا',         color: '#16A34A', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'rippling',        nameEn: 'Rippling',                  nameAr: 'ريبلينج',             category: 'hr', description: 'HR, IT & payroll platform',   descriptionAr: 'منصة HR وIT والرواتب',      color: '#F47521', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'hibob',           nameEn: 'HiBob',                     nameAr: 'هاي بوب',             category: 'hr', description: 'Modern HR platform',          descriptionAr: 'منصة HR عصرية',            color: '#7B4FFF', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'personio',        nameEn: 'Personio',                  nameAr: 'بيرسونيو',            category: 'hr', description: 'European HR software',        descriptionAr: 'برنامج HR أوروبي',          color: '#FF5C35', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'ukg',             nameEn: 'UKG (Kronos)',               nameAr: 'UKG كرونوس',          category: 'hr', description: 'Workforce management',         descriptionAr: 'إدارة القوى العاملة',       color: '#FF6D00', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },
  { id: 'sage-hr',         nameEn: 'Sage HR',                   nameAr: 'سيج HR',              category: 'hr', description: 'SME HR management',           descriptionAr: 'إدارة موارد بشرية للمنشآت', color: '#00B050', badge: 'API Ready',    badgeAr: 'API جاهز',    region: 'global' },

  // ══════════════════════════════════════════════════════
  //  🛒  MARKETPLACE & eCOMMERCE  (16 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'salla',           nameEn: 'Salla',                     nameAr: 'سلة',                 category: 'marketplace', description: 'Saudi e-commerce platform',     descriptionAr: 'منصة التجارة الإلكترونية السعودية', color: '#5B4FBE', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'ksa',    featured: true },
  { id: 'zid',             nameEn: 'Zid',                       nameAr: 'زد',                  category: 'marketplace', description: 'Saudi online store builder',    descriptionAr: 'منشئ المتاجر السعودي',             color: '#1D4ED8', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'ksa' },
  { id: 'nupco',           nameEn: 'Nupco',                     nameAr: 'نوبكو',               category: 'marketplace', description: 'Saudi B2B procurement',         descriptionAr: 'المشتريات B2B السعودية',            color: '#005B96', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'ksa',    featured: true },
  { id: 'noon-business',   nameEn: 'Noon Business',             nameAr: 'نون بيزنس',           category: 'marketplace', description: 'GCC B2B marketplace',           descriptionAr: 'سوق B2B للخليج',                   color: '#FEEE00', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'gcc' },
  { id: 'shopify',         nameEn: 'Shopify',                   nameAr: 'شوبيفاي',             category: 'marketplace', description: '#1 eCommerce platform',         descriptionAr: 'المنصة الأولى للتجارة الإلكترونية', color: '#96BF48', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'global', featured: true },
  { id: 'woocommerce',     nameEn: 'WooCommerce',               nameAr: 'ووكوميرس',            category: 'marketplace', description: 'WordPress eCommerce plugin',     descriptionAr: 'إضافة التجارة الإلكترونية',        color: '#7F54B3', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'global' },
  { id: 'magento',         nameEn: 'Magento (Adobe)',           nameAr: 'ماجنتو',              category: 'marketplace', description: 'Enterprise eCommerce',          descriptionAr: 'تجارة إلكترونية للمؤسسات',         color: '#EE672F', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'amazon-business', nameEn: 'Amazon Business',           nameAr: 'أمازون بيزنس',        category: 'marketplace', description: 'B2B procurement marketplace',   descriptionAr: 'سوق المشتريات B2B',                color: '#FF9900', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'alibaba',         nameEn: 'Alibaba.com',               nameAr: 'علي بابا',            category: 'marketplace', description: 'Global B2B marketplace',        descriptionAr: 'سوق B2B العالمي',                  color: '#FF6A00', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'bigcommerce',     nameEn: 'BigCommerce',               nameAr: 'بيج كوميرس',          category: 'marketplace', description: 'Enterprise eCommerce platform', descriptionAr: 'منصة تجارة إلكترونية',             color: '#009BDE', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'prestashop',      nameEn: 'PrestaShop',                nameAr: 'بريستا شوب',          category: 'marketplace', description: 'Open source eCommerce',         descriptionAr: 'تجارة إلكترونية مفتوحة',           color: '#DF0067', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'opencart',        nameEn: 'OpenCart',                  nameAr: 'أوبن كارت',           category: 'marketplace', description: 'Free eCommerce solution',       descriptionAr: 'حل تجارة إلكترونية مجاني',         color: '#27A0D9', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'ebay-business',   nameEn: 'eBay Business',             nameAr: 'إي باي للأعمال',      category: 'marketplace', description: 'Global marketplace',            descriptionAr: 'السوق العالمي',                    color: '#E53238', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'lazada',          nameEn: 'Lazada',                    nameAr: 'لازادا',              category: 'marketplace', description: 'Southeast Asia marketplace',    descriptionAr: 'سوق جنوب شرق آسيا',               color: '#F57224', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'wix-stores',      nameEn: 'Wix Stores',                nameAr: 'ويكس للمتاجر',        category: 'marketplace', description: 'Website & store builder',       descriptionAr: 'بناء مواقع ومتاجر',               color: '#0C6EFC', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'squarespace',     nameEn: 'Squarespace',               nameAr: 'سكوير سبيس',          category: 'marketplace', description: 'Website & eCommerce builder',   descriptionAr: 'بناء مواقع وتجارة إلكترونية',     color: '#000000', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },

  // ══════════════════════════════════════════════════════
  //  🔐  SECURITY & COMPLIANCE  (12 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'ssl-tls',         nameEn: 'SSL / TLS Encryption',      nameAr: 'تشفير SSL/TLS',        category: 'security', description: '256-bit encrypted connections', descriptionAr: 'اتصالات مشفرة 256-bit',         color: '#00843D', badge: 'Active',       badgeAr: 'نشط',         region: 'global', featured: true },
  { id: 'pci-dss-sec',     nameEn: 'PCI DSS Compliant',         nameAr: 'PCI DSS متوافق',        category: 'security', description: 'Payment card security',         descriptionAr: 'أمان بطاقات الدفع',             color: '#003087', badge: 'Compliant',    badgeAr: 'ممتثل',       region: 'global', featured: true },
  { id: 'cloudflare-sec',  nameEn: 'Cloudflare Security',       nameAr: 'حماية كلاودفلير',       category: 'security', description: 'DDoS protection & WAF',         descriptionAr: 'حماية DDoS وجدار حماية',       color: '#F48120', badge: 'Active',       badgeAr: 'نشط',         region: 'global' },
  { id: 'palo-alto',       nameEn: 'Palo Alto Networks',        nameAr: 'بالو ألتو نتووركس',     category: 'security', description: 'Next-gen firewall & security',  descriptionAr: 'جدار حماية الجيل القادم',       color: '#FA582D', badge: 'Certified',    badgeAr: 'معتمد',       region: 'global' },
  { id: 'crowdstrike',     nameEn: 'CrowdStrike Falcon',        nameAr: 'كراود سترايك',          category: 'security', description: 'Cloud-native endpoint security', descriptionAr: 'أمان النقاط الطرفية السحابية',  color: '#E1393A', badge: 'Certified',    badgeAr: 'معتمد',       region: 'global' },
  { id: 'fortinet-sec',    nameEn: 'Fortinet',                  nameAr: 'فورتي نت',              category: 'security', description: 'Network security solutions',     descriptionAr: 'حلول أمن الشبكات',             color: '#DA1F26', badge: 'Certified',    badgeAr: 'معتمد',       region: 'global' },
  { id: 'sophos',          nameEn: 'Sophos',                    nameAr: 'سوفوس',                category: 'security', description: 'Cybersecurity as a service',    descriptionAr: 'أمن سيبراني كخدمة',            color: '#003C8F', badge: 'Certified',    badgeAr: 'معتمد',       region: 'global' },
  { id: 'trend-micro',     nameEn: 'Trend Micro',               nameAr: 'تريند مايكرو',          category: 'security', description: 'Cloud & network security',       descriptionAr: 'أمان سحابي وشبكات',            color: '#D71920', badge: 'Certified',    badgeAr: 'معتمد',       region: 'global' },
  { id: 'sentinelone',     nameEn: 'SentinelOne',               nameAr: 'سينتينل ون',            category: 'security', description: 'AI-powered security platform',  descriptionAr: 'منصة أمان مدعومة بالذكاء',      color: '#6A2BE9', badge: 'Certified',    badgeAr: 'معتمد',       region: 'global' },
  { id: 'veeam-backup',    nameEn: 'Veeam Backup',              nameAr: 'Veeam نسخ احتياطي',     category: 'security', description: 'Data backup & recovery',         descriptionAr: 'النسخ الاحتياطي واستعادة البيانات', color: '#00B336', badge: 'Active',  badgeAr: 'نشط',         region: 'global' },
  { id: 'onepass',         nameEn: '1Password Business',        nameAr: 'ون باسووورد',           category: 'security', description: 'Password & secrets management',  descriptionAr: 'إدارة كلمات المرور والأسرار',   color: '#1A8CFF', badge: 'Active',       badgeAr: 'نشط',         region: 'global' },
  { id: 'gdpr-comp',       nameEn: 'GDPR Compliance',           nameAr: 'امتثال GDPR',           category: 'security', description: 'EU data protection regulation',  descriptionAr: 'لوائح حماية البيانات الأوروبية', color: '#003087', badge: 'Compliant',   badgeAr: 'ممتثل',       region: 'global' },

  // ══════════════════════════════════════════════════════
  //  📅  RESERVATIONS & DINING  (12 شريك)
  // ══════════════════════════════════════════════════════
  { id: 'eat-app',         nameEn: 'Eat App',                   nameAr: 'Eat تطبيق',           category: 'reservation', description: 'Restaurant reservation platform', descriptionAr: 'منصة حجز مطاعم',             color: '#FF4444', badge: 'Full Sync',    badgeAr: 'تزامن كامل', region: 'gcc',    featured: true },
  { id: 'thefork',         nameEn: 'TheFork (TripAdvisor)',     nameAr: 'ذا فورك',             category: 'reservation', description: 'Restaurant booking & reviews',   descriptionAr: 'حجز مطاعم وتقييمات',         color: '#00B050', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'opentable',       nameEn: 'OpenTable',                 nameAr: 'أوبن تيبل',           category: 'reservation', description: 'World\'s largest reservation',   descriptionAr: 'أكبر نظام حجز في العالم',    color: '#DA3743', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global', featured: true },
  { id: 'resy',            nameEn: 'Resy',                      nameAr: 'ريزي',                category: 'reservation', description: 'Premium dining reservations',    descriptionAr: 'حجوزات مطاعم فاخرة',         color: '#1A1A1A', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'tablecheck',      nameEn: 'TableCheck',                nameAr: 'تيبل تشيك',           category: 'reservation', description: 'Restaurant management',          descriptionAr: 'إدارة مطاعم وحجوزات',        color: '#1A1A2E', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'sevenrooms',      nameEn: 'SevenRooms',                nameAr: 'سيفن رومز',           category: 'reservation', description: 'Guest management platform',      descriptionAr: 'إدارة الضيوف والحجوزات',     color: '#2C3E50', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'quandoo',         nameEn: 'Quandoo',                   nameAr: 'كواندو',              category: 'reservation', description: 'Restaurant discovery & booking', descriptionAr: 'اكتشاف وحجز مطاعم',          color: '#FF6B00', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'gloriaFood',      nameEn: 'GloriaFood',                nameAr: 'جلوريا فود',          category: 'reservation', description: 'Free online ordering system',    descriptionAr: 'نظام طلبات إلكتروني مجاني',  color: '#FF5722', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'yelp-res',        nameEn: 'Yelp Reservations',         nameAr: 'يلب للحجوزات',        category: 'reservation', description: 'Business listings & reservations',descriptionAr: 'قوائم الأعمال والحجوزات',    color: '#D32323', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'tripadvisor',     nameEn: 'TripAdvisor Restaurants',   nameAr: 'تريب أدفايزر',        category: 'reservation', description: 'Restaurant reviews & bookings',  descriptionAr: 'مراجعات وحجوزات مطاعم',      color: '#34E0A1', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
  { id: 'google-reserve',  nameEn: 'Google Reserve',            nameAr: 'Google Reserve',     category: 'reservation', description: 'Book via Google Search & Maps',  descriptionAr: 'حجز عبر بحث جوجل والخرائط', color: '#4285F4', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global', featured: true },
  { id: 'zenchef',         nameEn: 'Zenchef',                   nameAr: 'زن شيف',              category: 'reservation', description: 'European restaurant platform',   descriptionAr: 'منصة مطاعم أوروبية',         color: '#2D6A4F', badge: 'API Ready',    badgeAr: 'API جاهز',   region: 'global' },
];

export function getPartnersByCategory(cat: PartnerCategory): TechPartner[] {
  return TECH_PARTNERS.filter(p => p.category === cat);
}

export function getFeaturedPartners(): TechPartner[] {
  return TECH_PARTNERS.filter(p => p.featured);
}

export function getKsaPartners(): TechPartner[] {
  return TECH_PARTNERS.filter(p => p.region === 'ksa');
}

export function searchTechPartners(query: string): TechPartner[] {
  const q = query.toLowerCase();
  return TECH_PARTNERS.filter(p =>
    p.nameEn.toLowerCase().includes(q) ||
    p.nameAr.includes(q) ||
    p.descriptionAr.includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.category.toLowerCase().includes(q)
  );
}
